Vue.component('faq_accordion_1721648766', {
  template: `
    <div>
      <section class="leading-relaxed max-w-screen-xl mt-12 mx-auto px-4 md:px-8 bg-white">
        <div class="space-y-3 text-center">
          <h1 class="text-4xl text-gray-800 font-semibold pt-10">Blockchain Data Analysis FAQ</h1>
          <p class="text-gray-600 max-w-lg mx-auto text-lg">Get answers to common questions about our blockchain data analysis platform</p>
        </div>
        <div class="mt-14 max-w-2xl mx-auto">
          <div v-for="(item, index) in faqs" :key="index" class="space-y-5 mt-5 overflow-hidden border-b border-gray-200 hover:bg-gray-50 cursor-pointer" @click="toggleFaq(index)">
            <h4 class="cursor-pointer pb-5 flex items-center justify-between text-lg text-gray-700 font-medium">
              { item.q }
              <svg v-if="selectedFaq === index" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-500 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 12H4"/></svg>
              <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-500 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
            </h4>
            <div v-show="selectedFaq === index" style="overflow: hidden; transition: max-height 0.5s ease-in-out, opacity 0.5s ease-in-out;" :style="{ maxHeight: selectedFaq === index ? '1000px' : '0px', opacity: selectedFaq === index ? 1 : 0 }">
              <div class="px-4 py-6">
                <p class="text-gray-700 pb-4 max-w-full text-lg">{ item.a }</p>
              </div>
            </div>
            <br/><br/>
          </div>
        </div>
      </section>
    </div>
  `,
  delimiters: ['{', '}'],
  data() {
    return {
      selectedFaq: null,
      faqs: [
        {
          q: "What is blockchain data analysis?",
          a: "Blockchain data analysis involves extracting insights from the vast amounts of data generated by blockchain networks. Our platform provides tools to monitor, query, and analyze this data in real-time."
        },
        {
          q: "What blockchain networks do you support?",
          a: "We currently support analysis for Bitcoin, Ethereum, and several other major blockchain networks. Our roadmap includes adding support for more networks based on customer demand."
        },
        {
          q: "How can I access the blockchain data?",
          a: "You can access the data through our intuitive web interface, API, or by connecting business intelligence tools directly to our databases."
        },
        {
          q: "What kind of insights can I get?",
          a: "Our platform enables analysis of transaction patterns, smart contract activity, network statistics, and more. You can slice and dice the data in endless ways to uncover valuable blockchain insights."
        },
        {
          q: "Is my data secure and private?",
          a: "Absolutely. We employ industry-leading security practices and never share or sell your data to third parties. Privacy is one of our core principles."
        }
      ]
    }
  },
  methods: {
    toggleFaq(index) {
      this.selectedFaq = this.selectedFaq === index ? null : index;
    }
  }
});